# Generated by Django 4.2.2 on 2023-07-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=255)),
                ('start_time', models.IntegerField()),
                ('finish_time', models.IntegerField()),
                ('min_bid', models.IntegerField()),
                ('bidders', models.JSONField(default=list)),
                ('members', models.JSONField(default=list)),
                ('public_auction', models.BooleanField(default=False)),
            ],
        ),
    ]
