# Generated by Django 4.2.2 on 2023-07-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='finish_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
