# Generated by Django 4.2.2 on 2023-07-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0002_alter_contract_finish_time_alter_contract_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='bidders',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='members',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
