# Generated by Django 4.2.3 on 2023-07-09 08:25

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Auction', '0003_alter_contract_bidders_alter_contract_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('wallet_address', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='contract',
            name='bidders',
        ),
        migrations.AlterField(
            model_name='contract',
            name='min_bid',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.FloatField()),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transition', to='Auction.contract')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transition', to='Auction.customuser')),
            ],
        ),
    ]
