# Generated by Django 4.2.2 on 2023-07-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0007_alter_contract_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='members',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
