# Generated by Django 4.2.2 on 2023-07-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0010_contract_bidders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='members',
        ),
        migrations.AddField(
            model_name='contract',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to='Auction.customuser'),
        ),
    ]
