# Generated by Django 4.2.2 on 2023-09-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0011_remove_contract_members_contract_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_done',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
